### ISSUE TITLE
Uruchomienie Symfony

### ISSUE THREAD

**Issue by nurzynskipawel** [nurzynskipawel/ecommerce#13]

**Comment by pwlap** [comment]
Potrzebuję od Ciebie (żebym mógł sprawdzić faktycznie czy poprawnie uruchomiłeś Symfony)
- [ ] konfiguracja `nginxa` 
  - najlepiej zrobić to przez wrzucenie informacje do `README.md` (reszte niepotrzebnych rzeczy z tego usuń) 
  - commit z podlinkowaniem do tego `issue` (w commit message dodaj `hash issue`)
- [ ] usuń niepotrzebny plik `readme.txt`
- [ ] wszystkie zmiany mają być na oddzielnym `branchu` (żebym potem mógł zrobić `Pull Request`)
- [ ] dodatkowo dodaj opis jak odpalić ten projekt lokalnie (najlepiej jakaś prosta słowna instrukcja)

**Comment by nurzynskipawel** [comment]
Tylko o odpaleniu projektu lokalnie to narazie krótką informację dam i zrobię commita

**Comment by pwlap** [comment]
Małe kolejne elementy do poprawy:
- [ ] wykluczenie katalogi `.idea` z repozytorium
- [ ] nastepny `commit` ma mieć w `commit message` opis tego co faktycznie zrobiłeś, a nie opis z którego nie da się zrozumieć co zrobiłeś :) (zapis "#13 Done" nic nie mówi, mogłeś wrzucić "#13 Dodanie konfiguracji nginxa oraz usunięcie zbędnych plików")
